services:
  mysql:
    image: mysql
    container_name: mysql-calendar
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=calendar
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis
    container_name: redis-calendar
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

volumes:
  mysql-data:
  redis-data: