services:
  mysql:
    image: mysql
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=calendar
    volumes:
      - mysql-data:/var/lib/mysql
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: always

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./selfsigned.crt:/etc/ssl/certs/selfsigned.crt
      - ./selfsigned.key:/etc/ssl/private/selfsigned.key
    ports:
      - "443:443" # HTTPS 포트
      - "80:80"   # HTTP 포트 (Optional)
    restart: always

volumes:
  mysql-data:
  redis-data: