services:
  redis:
    image: redis
    container_name: redis
    hostname: redis
    ports:
      - "6379:6379"

  spring-app:
    image: chanheess/chcalendar
    container_name: spring-app
    ports:
      - "8080:8080"
    env_file:
      - .env
    volumes:
      - ${SERVICE_ACCOUNT_FILE}:${SERVICE_ACCOUNT_FILE}:ro
    depends_on:
      - redis

  certbot:
    image: certbot/certbot:latest
    container_name: certbot
    volumes:
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/www:/var/www/html
    environment:
      - EMAIL=${EMAIL}
      - DOMAIN=${DOMAIN}
    # entrypoint: 무한 루프를 통해 6시간마다 갱신 시도
    entrypoint: >
      /bin/sh -c "while :; do certbot renew --non-interactive; sleep 6h; done"
    restart: unless-stopped

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./data/letsencrypt:/etc/letsencrypt
      - ./data/www:/var/www/html
      - type: bind
        source: /var/www/html/frontend/build
        target: /var/www/html/frontend/build
    depends_on:
      - spring-app
    restart: always
