spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${DB_PASSWORD}
    url: ${DB_URL}
    username: ${DB_USERNAME}
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mail:
    smtp:
      host: "smtp.gmail.com"
      port: 587                            # Google STMP 포트 번호
      username: ${SMTP_EMAIL}
      password: ${SMTP_EMAIL_PASSWORD}
      properties:
        mail:
          smtp:
            auth: true
            starttls:
              enable: true
            connectiontimeout: 5000
            timeout: 5000
            writetimeout: 5000
      auth-code-expiration-millis: 1800000 #인증 코드 만료시간

jwt:
  secret: ${JWT_SECRET}
logging:
  level:
    org.hibernate.SQL: debug