spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587                            # Gmail SMTP 포트
    username: ${SMTP_EMAIL}              # 환경 변수에서 이메일 가져오기
    password: ${SMTP_EMAIL_PASSWORD}     # 환경 변수에서 비밀번호 가져오기
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  redis:
    host: ${REDIS_HOST}
    port: 6379
    env_file:
      - .env

server:
  forward-headers-strategy: native
  use-forward-headers: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug