spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1231
    url: jdbc:mysql://localhost:3306/calendar?rewriteBatchedStatements=true&profileSQL=true&logger=Slf4JLogger&maxQuerySizeToLog=999999
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      format_sql: true
      show_sql: true
jwt:
  secret: ${JWT_SECRET}
