spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: 1231
    url: jdbc:mysql://localhost:3306/calendar
    username: root
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl