spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
      format_sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USERNAME}
    password: ${SMTP_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true
          starttls.required: true
          ssl.trust: ${SMTP_HOST}

  redis:
    host: ${REDIS_HOST}
    port: 6379
    env_file:
      - .env

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - https://www.googleapis.com/auth/calendar

server:
  forward-headers-strategy: native
  use-forward-headers: true

jwt:
  secret: ${JWT_SECRET}

logging:
  level:
    org.hibernate.SQL: debug

password:
  reset:
    url: ${DOMAIN}

vapid:
  publicKey: ${VAPID_PUBLIC_KEY}
  privateKey: ${VAPID_PRIVATE_KEY}

firebase:
  service-account-file: ${SERVICE_ACCOUNT_FILE}

home_url: ${HOME_URL}